name: Run library unit tests

on: 
  push:
    paths: ['Frontend/library/**']
  pull_request:
    paths: ['Frontend/library/**']

env:
  NODE_VERSION: 18.17.x

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    permissions:
      contents: write
    steps:
    - name: "Checkout source code"
      uses: actions/checkout@v3

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: "${{ env.NODE_VERSION }}"
        registry-url: 'https://registry.npmjs.org'

    - name: Install library deps
      working-directory: ./Frontend/library
      run: npm ci

    - name: Run frontend lib tests
      working-directory: ./Frontend/library
      run: npm run test
